use axiom_codec::{
    constants::{USER_MAX_OUTPUTS, USER_MAX_SUBQUERIES, USER_RESULT_FIELD_ELEMENTS},
    types::field_elements::SUBQUERY_RESULT_LEN,
};

pub const SUBQUERY_NUM_INSTANCES: usize = USER_MAX_SUBQUERIES * SUBQUERY_RESULT_LEN;
pub const USER_OUTPUT_NUM_INSTANCES: usize = USER_MAX_OUTPUTS * USER_RESULT_FIELD_ELEMENTS;
