export declare const chainConfig: {
    readonly formatters: {
        readonly block: {
            exclude: [] | undefined;
            format: (args: import("../types/utils.js").Assign<import("../index.js").ExactPartial<import("../index.js").RpcBlock>, import("./index.js").ZkSyncRpcBlockOverrides & {
                transactions: `0x${string}`[] | import("./index.js").ZkSyncRpcTransaction[];
            }>) => {
                baseFeePerGas: bigint | null;
                blobGasUsed: bigint;
                difficulty: bigint;
                excessBlobGas: bigint;
                extraData: `0x${string}`;
                gasLimit: bigint;
                gasUsed: bigint;
                hash: `0x${string}` | null;
                logsBloom: `0x${string}` | null;
                miner: `0x${string}`;
                mixHash: `0x${string}`;
                nonce: `0x${string}` | null;
                number: bigint | null;
                parentHash: `0x${string}`;
                receiptsRoot: `0x${string}`;
                sealFields: `0x${string}`[];
                sha3Uncles: `0x${string}`;
                size: bigint;
                stateRoot: `0x${string}`;
                timestamp: bigint;
                totalDifficulty: bigint | null;
                transactions: `0x${string}`[] | import("./index.js").ZkSyncTransaction[];
                transactionsRoot: `0x${string}`;
                uncles: `0x${string}`[];
                withdrawals?: import("../index.js").Withdrawal[] | undefined;
                withdrawalsRoot?: `0x${string}` | undefined;
                l1BatchNumber: bigint | null;
                l1BatchTimestamp: bigint | null;
            } & {};
            type: "block";
        };
        readonly transaction: {
            exclude: [] | undefined;
            format: (args: import("../types/utils.js").Assign<import("../index.js").ExactPartial<import("../index.js").RpcTransaction>, import("./index.js").ZkSyncRpcTransaction>) => ({
                r: `0x${string}`;
                s: `0x${string}`;
                v: bigint;
                to: `0x${string}` | null;
                from: `0x${string}`;
                gas: bigint;
                nonce: number;
                value: bigint;
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                hash: `0x${string}`;
                input: `0x${string}`;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                gasPrice: bigint;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobVersionedHashes?: undefined;
                chainId?: number | undefined;
                yParity?: undefined;
                type: "legacy";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                r: `0x${string}`;
                s: `0x${string}`;
                v: bigint;
                to: `0x${string}` | null;
                from: `0x${string}`;
                gas: bigint;
                nonce: number;
                value: bigint;
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                hash: `0x${string}`;
                input: `0x${string}`;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                gasPrice: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList?: undefined;
                blobVersionedHashes?: undefined;
                chainId?: number | undefined;
                yParity: number;
                type: "priority";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                r: `0x${string}`;
                s: `0x${string}`;
                v: bigint;
                to: `0x${string}` | null;
                from: `0x${string}`;
                gas: bigint;
                nonce: number;
                value: bigint;
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                hash: `0x${string}`;
                input: `0x${string}`;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                gasPrice: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList?: undefined;
                blobVersionedHashes?: undefined;
                chainId?: number | undefined;
                yParity: number;
                type: "priority" | "eip712";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice: bigint;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "eip2930";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "eip1559";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "priority";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "priority" | "eip712";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice: bigint;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: undefined;
                maxPriorityFeePerGas: undefined;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "eip2930";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "eip1559";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "priority";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes?: undefined;
                chainId: number;
                type: "priority" | "eip712";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas: bigint;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes: `0x${string}`[];
                chainId: number;
                type: "eip4844";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes: `0x${string}`[];
                chainId: number;
                type: "priority";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            } | {
                blockHash: `0x${string}` | null;
                blockNumber: bigint | null;
                from: `0x${string}`;
                gas: bigint;
                hash: `0x${string}`;
                input: `0x${string}`;
                nonce: number;
                r: `0x${string}`;
                s: `0x${string}`;
                to: `0x${string}` | null;
                transactionIndex: number | null;
                typeHex: `0x${string}` | null;
                v: bigint;
                value: bigint;
                yParity: number;
                gasPrice?: undefined;
                maxFeePerBlobGas: undefined;
                maxFeePerGas: bigint;
                maxPriorityFeePerGas: bigint;
                accessList: import("../index.js").AccessList;
                blobVersionedHashes: `0x${string}`[];
                chainId: number;
                type: "priority" | "eip712";
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
            }) & {};
            type: "transaction";
        };
        readonly transactionReceipt: {
            exclude: [] | undefined;
            format: (args: import("../types/utils.js").Assign<import("../index.js").ExactPartial<import("../index.js").RpcTransactionReceipt>, import("./index.js").ZkSyncRpcTransactionReceiptOverrides>) => {
                blobGasPrice?: bigint | undefined;
                blobGasUsed?: bigint | undefined;
                blockHash: `0x${string}`;
                blockNumber: bigint;
                contractAddress: `0x${string}` | null | undefined;
                cumulativeGasUsed: bigint;
                effectiveGasPrice: bigint;
                from: `0x${string}`;
                gasUsed: bigint;
                logs: import("./index.js").ZkSyncLog[];
                logsBloom: `0x${string}`;
                root?: `0x${string}` | undefined;
                status: "success" | "reverted";
                to: `0x${string}` | null;
                transactionHash: `0x${string}`;
                transactionIndex: number;
                type: import("./index.js").ZkSyncTransactionType;
                l1BatchNumber: bigint | null;
                l1BatchTxIndex: bigint | null;
                l2ToL1Logs: import("./index.js").ZkSyncL2ToL1Log[];
            } & {};
            type: "transactionReceipt";
        };
        readonly transactionRequest: {
            exclude: ("gasPerPubdata" | "paymaster" | "factoryDeps" | "paymasterInput" | "customSignature")[] | undefined;
            format: (args: ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip2930" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip1559" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster: `0x${string}`;
                paymasterInput: `0x${string}`;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster?: undefined;
                paymasterInput?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip2930" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip1559" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster: `0x${string}`;
                paymasterInput: `0x${string}`;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster?: undefined;
                paymasterInput?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip2930" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip1559" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster: `0x${string}`;
                paymasterInput: `0x${string}`;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster?: undefined;
                paymasterInput?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "legacy" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip2930" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                to?: `0x${string}` | null | undefined;
                value?: bigint | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "eip1559" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to: `0x${string}` | null;
                gasPrice?: undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas: bigint;
                accessList?: import("../index.js").AccessList | undefined;
                blobs: readonly `0x${string}`[] | readonly Uint8Array[];
                type?: "eip4844" | undefined;
            } & {
                gasPerPubdata?: undefined;
                customSignature?: undefined;
                paymaster?: undefined;
                paymasterInput?: undefined;
                factoryDeps?: undefined;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster: `0x${string}`;
                paymasterInput: `0x${string}`;
            }) | ({
                data?: `0x${string}` | undefined;
                from?: `0x${string}`;
                gas?: bigint | undefined;
                nonce?: number | undefined;
                value?: bigint | undefined;
                to?: `0x${string}` | null | undefined;
                gasPrice?: bigint | undefined;
                maxFeePerGas?: bigint | undefined;
                maxPriorityFeePerGas?: bigint | undefined;
                maxFeePerBlobGas?: bigint | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: readonly `0x${string}`[] | readonly Uint8Array[] | undefined;
                type?: "legacy" | "eip1559" | "eip4844" | "eip2930" | "priority" | "eip712" | undefined;
            } & Omit<import("../index.js").TransactionRequestBase, "type"> & import("../index.js").ExactPartial<import("../index.js").FeeValuesEIP1559> & {
                gasPerPubdata?: bigint | undefined;
                customSignature?: `0x${string}` | undefined;
                factoryDeps?: `0x${string}`[] | undefined;
                type?: "priority" | "eip712" | undefined;
            } & {
                paymaster?: undefined;
                paymasterInput?: undefined;
            })) => ({
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "0x0" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "0x1" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "0x2" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: undefined;
                blobs?: undefined;
                type: "0xff" | "0x71";
                eip712Meta: import("./index.js").ZkSyncEip712Meta;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "0x0" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "0x1" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "0x2" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type: "0xff" | "0x71";
                eip712Meta: import("./index.js").ZkSyncEip712Meta;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: undefined;
                blobs?: undefined;
                type?: "0x0" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: `0x${string}` | undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: undefined;
                maxPriorityFeePerGas?: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "0x1" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type?: "0x2" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                to?: `0x${string}` | null | undefined;
                value?: `0x${string}` | undefined;
                gasPrice?: undefined;
                maxFeePerBlobGas?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs?: undefined;
                type: "0xff" | "0x71";
                eip712Meta: import("./index.js").ZkSyncEip712Meta;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                value?: `0x${string}` | undefined;
                to: `0x${string}` | null;
                gasPrice?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                maxFeePerBlobGas: `0x${string}`;
                accessList?: import("../index.js").AccessList | undefined;
                blobs: readonly `0x${string}`[] | readonly Uint8Array[];
                type?: "0x3" | undefined;
                eip712Meta?: undefined;
            } | {
                data?: `0x${string}` | undefined;
                from: `0x${string}`;
                gas?: `0x${string}` | undefined;
                nonce?: `0x${string}` | undefined;
                value?: `0x${string}` | undefined;
                to: `0x${string}` | null | undefined;
                gasPrice?: undefined;
                maxFeePerGas?: `0x${string}` | undefined;
                maxPriorityFeePerGas?: `0x${string}` | undefined;
                maxFeePerBlobGas: undefined;
                accessList?: import("../index.js").AccessList | undefined;
                blobs: readonly `0x${string}`[] | readonly Uint8Array[];
                type: "0xff" | "0x71";
                eip712Meta: import("./index.js").ZkSyncEip712Meta;
            }) & {
                gasPerPubdata: never;
                paymaster: never;
                factoryDeps: never;
                paymasterInput: never;
                customSignature: never;
            };
            type: "transactionRequest";
        };
    };
    readonly serializers: {
        readonly transaction: typeof import("./serializers.js").serializeTransaction;
    };
    readonly custom: {
        readonly getEip712Domain: import("./index.js").EIP712DomainFn<import("./index.js").ZkSyncTransactionSerializable, import("./index.js").ZkSyncEIP712TransactionSignable>;
    };
};
//# sourceMappingURL=chainConfig.d.ts.map